### ISSUE TITLE
Can you update for deprecation of python-dufte

### ISSUE THREAD

**Issue by graysky2** [nschloe/stressberry#118]
I see [dufte](https://github.com/nschloe/dufte#deprecation) is deprecated and replaced.  Can you update stressberry to work with the replacement?  When I try:
```
% stressberry-run -n "comments" fan.dat                                                           
Awaiting stable baseline temperature...
...
% stressberry-plot -o caseless.png -f -l 200 2200 -t 20 90 fan.dat 
Traceback (most recent call last):
  File "/usr/bin/stressberry-plot", line 8, in <module>
    sys.exit(plot())
  File "/usr/lib/python3.9/site-packages/stressberry/cli/plot.py", line 9, in plot
    import dufte
ModuleNotFoundError: No module named 'dufte'
```

Upstream or am I doing something wrong?

**Comment by graysky2** [comment]
Ah, is it as simple are removing line 9 from `plot.py`?

https://github.com/nschloe/stressberry/blob/main/stressberry/cli/plot.py#L9

**Comment by nschloe** [comment]
Deprecation is just a warning, I'll get to it at some point.

**Comment by graysky2** [comment]
Ah, is it as simple are removing line 9 from plot.py?

https://github.com/nschloe/stressberry/blob/main/stressberry/cli/plot.py#L9
