### ISSUE TITLE
ModuleNotFoundError: No module named 'stressberry'

### ISSUE THREAD

**Issue by crackedpotato007** [nschloe/stressberry#124]
Hey! I installed the program from paru and am unable to run it and keep getting 
```
  File "/usr/bin/stressberry-run", line 5, in <module>
    from stressberry.cli import run
ModuleNotFoundError: No module named 'stressberry'
```

**Comment by nschloe** [comment]
That's a paru issue then.

**Comment by crackedpotato007** [comment]
> That's a paru issue then.
Hey, man thats not a paru issue. Please at least hear the person out before closing out the issue

**Comment by nschloe** [comment]
The Python package works perfectly. What else should be the issue? Could also be a local config on your side.

**Comment by crackedpotato007** [comment]
Installing python normally from pacman works good but with pyenv doesn't
