### ISSUE TITLE
Rpi 4 4gb, Active cooled and Passive Results

### ISSUE THREAD

**Issue by flyingferret** [nschloe/stressberry#21]
My Setup
Dual fan heatsink with MX-4 for the CPU an additional smaller copper heatink on the ram and thermal pads to make up the hight to the main heatsink.  PoE pins removed for space and a thin thermal pad on the Wifi chip to help hold down the large heatsink....any maybe cool the wifi chip

![20190703_183421](https://user-images.githubusercontent.com/5098346/60612909-b4dad500-9dc1-11e9-9808-ca91cb3dbb35.jpg)

[RPI_4_Heat sink with fan off and ON .zip](https://github.com/nschloe/stressberry/files/3356219/RPI_4_Heat.sink.with.fan.off.and.ON.zip)

![mix](https://user-images.githubusercontent.com/5098346/60612963-d20fa380-9dc1-11e9-8c12-4633cc34d450.png)

Fan Off peaks at 62°C  and Fans ON  peaked at 42°C
Very quite fans not scilent  , but measured at 33db from 6" away.

**Comment by nschloe** [comment]
Super cool! Looks like peak temperature hasn't been reached yet for the naked version. Maybe we should stress it for longer? Anyways, awesome project!

**Comment by flyingferret** [comment]
My error forgot to do the runs while naked this was actually for fans OFF and fans ON

**Comment by nschloe** [comment]
Alright, I included it in the main readme. Thanks again!
