### ISSUE TITLE
Stress test with a  Hex Wrench case

### ISSUE THREAD

**Issue by patrickpoirier51** [nschloe/stressberry#45]
Hell, Thanks for the test suite

Here are my results with the  Hex Wrench case:
![image](https://user-images.githubusercontent.com/12484190/68396176-1f6c9a80-013f-11ea-9248-26fb326033cf.png)

It is used on a JETBOT car running with a  RPI4 and Google Coral stick for TensorFlow object avoidance Machine Learning. Take note that I used the test to make sure that my GPIO fed 5 Volts supply was OK == So far, so good.

![image](https://user-images.githubusercontent.com/12484190/68396323-6490cc80-013f-11ea-9684-62e504dca232.png)

Here is the file (had to rename to txt):

[out.txt](https://github.com/nschloe/stressberry/files/3820053/out.txt)

**Comment by nschloe** [comment]
Thanks, added this to the main README. #46
