### ISSUE TITLE
ProgPi passiv cooling case

### ISSUE THREAD

**Issue by progpi** [nschloe/stressberry#53]
My temperature measurements on Pi 4 are done with some scripts based on sysbench + stressberry-plot Picture from my Pi 4 cooling solution : 
https://progpi.de/cpu-stresstestverfahren/

Temperatures under 50°C after 60 min of stresstest.

**Comment by nschloe** [comment]
If you'd like me to include the data into the main readme, you'll actually have to post the data here.

**Comment by progpi** [comment]
A cylindric piece of copper is above the Pi 4 SoC and combined with heatsinks for LED's
![pi4_CuZyl50_duo](https://user-images.githubusercontent.com/58991507/71547399-f084df00-299f-11ea-92d4-5bade37a298d.jpg)

The used case is StackBT (Reichelt) but has many different names. My temperature measurements on Pi 4 are done with some scripts based on sysbench + stressberry-plot 
 
![plotrun_JoyIT_ProgPi](https://user-images.githubusercontent.com/58991507/71547362-6fc5e300-299f-11ea-8b21-68e740c395aa.jpg)

Done with 60 min of sysbench (4 core Test).  Due to the specific heat capacity of copper a shorter test time doesn't give representative temperatures. More info here : 
https://progpi.de/cpu-stresstestverfahren/

**Comment by nschloe** [comment]
All very nice, thanks for sharing your experiments here! I'll close the report since there nothing actionable for stressberry now, but feel free to add more information for others to find.

**Comment by progpi** [comment]
Will the ProgPi-Case (with copper/wood cover plate) become visible on "main readme" ?

**Comment by nschloe** [comment]
That's only possible of you post the data here.

**Comment by progpi** [comment]
my data files are for a cycle of 10+60+10 Minutes with Temperature measurement in 10 sec steps 
[pi4cpu.zip](https://github.com/nschloe/stressberry/files/4014693/pi4cpu.zip)

**Comment by nschloe** [comment]
Okay, this is different from all other data in the readme so it'll be difficult to include those. Why not produce 5+10+5 files like all the others?

**Comment by progpi** [comment]
Well I could do so, but you see the temperature increasing a lot due to the capacity of copper plate, copper cylinder and the LED heatsinks. But I think it would be sufficient just to have a Link to this post like it is done with CooliPi

**Comment by nschloe** [comment]
The first diagram in the readme gives some ballpark figures, and for that it works quite alright. If you want to compare some heavy solutions where you need 1 degree precision, then that's best done on a separate page as you did.

**Comment by progpi** [comment]
Meanwhile I shortend my measurements to 15 min giving the following results
![plotrun15](https://user-images.githubusercontent.com/58991507/71666025-78cc0100-2d5f-11ea-88ee-9f2c5b4bb577.png)
ProgPi-Case is missing here because I have only one Pi4 with 2GB. Be free to test sberry-run15.sh
with your own cases. In the png there are some added *.dat coming from "IceTower"+CooliPi.
 sberry-run15.sh adds new measurements to *.cfg and starts then plotrun15.sh - easy to use I think.

**Comment by nschloe** [comment]
Okay, I've added some plots to the main readme now.
