### ISSUE TITLE
Ice Tower Low Profile Cooler - Test Results

### ISSUE THREAD

**Issue by leonhess** [nschloe/stressberry#54]
Hey there,
I did a bunch of tests using the Ice Tower Low Profile version Cooler.
[IceTowerResults.zip](https://github.com/nschloe/stressberry/files/3975362/IceTowerResults.zip)

![Ice Tower](https://wiki.52pi.com/images/thumb/d/d6/EP_0112_4b1.jpg/600px-EP_0112_4b1.jpg)
![Ice Tower with Noctua](https://user-images.githubusercontent.com/32615985/71032540-d7fe0480-2115-11ea-97b5-b9037ef6b33b.JPG)

I did tests without the Fan, with the Fan and also swapped the included Fan for a Noctua Fan. I also tested the Overclocking capabilities of this cooler.

For the Overclocks I used these settings:

| Frequency  | overvolt level |
| ------------- | ------------- |
| 1500 | 0 |
| 1750 | 2 |
| 2000 | 4 |
| 2147 | 6 |

Firmware:
```
BOOTLOADER: up-to-date
CURRENT: Tue 10 Sep 10:41:50 UTC 2019 (1568112110)
 LATEST: Tue 10 Sep 10:41:50 UTC 2019 (1568112110)
VL805: up-to-date
CURRENT: 000137ab
 LATEST: 000137ab
```

![all](https://user-images.githubusercontent.com/32615985/71032262-47272900-2115-11ea-9327-fb142332126e.png)

First of looking at the passive capabilities, you can see that Even a hefty overclock to 2147MHz is doable, though I am not quite sure if it has stabilised in 5 minutes.
![no_fan](https://user-images.githubusercontent.com/32615985/71032754-45aa3080-2116-11ea-872c-998a7ab574bc.png)

Then comparing the 2 used fans one can see that the Noctua is about 1-2 °C cooler but I think it also spins faster.
![fan_15](https://user-images.githubusercontent.com/32615985/71033005-d123c180-2116-11ea-9c20-b8949799bf19.png)
![fan_175](https://user-images.githubusercontent.com/32615985/71033007-d1bc5800-2116-11ea-9659-c8bf36d00c55.png)

Then here is a graph with all the results with the Noctua fan:
![noctua](https://user-images.githubusercontent.com/32615985/71033057-ebf63600-2116-11ea-8d45-7881ea8feefe.png)

And lastly I swapped the included thermal pad for some thermal grease which especially gave a big boost in performance for the 2.147GHz overclock.
![paste1500](https://user-images.githubusercontent.com/32615985/71033128-10eaa900-2117-11ea-9516-92d430ac1cf0.png)
![paste2147](https://user-images.githubusercontent.com/32615985/71033130-10eaa900-2117-11ea-92c3-4a7c14a0e666.png)

I am not sure how much of this you would want to include in README?

**Comment by nschloe** [comment]
Thanks, I've included some data in the main readme. Thanks in particular for the stock data, this had been sorely missing for a while!

**Comment by AmirulAndalib** [comment]
![out](https://github.com/nschloe/stressberry/assets/86344856/381c154b-097a-48fa-bb63-8e15d250ecb2)


Overvoltage 10

2321mhz cpu, 770mhz gpu
