### ISSUE TITLE
venv / virtualenv notes

### ISSUE THREAD

**Issue by clach04** [nschloe/stressberry#62]
I followed the instructions... sorta ;-) I created a virtualenv and then followed instructions. This did not go well for me. I saw all the errors described in issue #42. I believe this is due to me using:

    pip3 install stressberry --user

I also needed some packages to be installed and https://www.instructables.com/id/Stress-Testing-the-Raspberry-Pi/ was a good resource for me.

Once I removed the `--user` flag (in a new virtualenv) all was good. Not sure if this will help everyone but jotting down what I found.

**Comment by nschloe** [comment]
Remove `--user` from the instructions. pip 20+ does the right thing anyway.
