### ISSUE TITLE
stressberry-run take a long time to start

### ISSUE THREAD

**Issue by clach04** [nschloe/stressberry#64]
stressberry-run imports matplotlib and numpy - even though they are not used.

On some distributions, those libraries may not be available. Can these be made optional or only for stressberry-plot?

**Comment by nschloe** [comment]
Good call. Numpy snuck in there by accident, removed now. mpl is also more isolated now. I _could_ make it an `extra_dependency`, but refrained from doing so for now since I presume many people would trip over this. (stressberry is used by many non-experts.)
