### ISSUE TITLE
Problem with plotting

### ISSUE THREAD

**Issue by Protic1** [nschloe/stressberry#81]
Hi there,
I have used Stressberry for testing heatsinks on raspberry pi 4, but I have run in some trouble while trying to plot data. To be specific I had trouble removing data labels. 
I don't know if this problem is standard or I have done something wrong but I fixed my problem by changing some code in plot.py file from code.
Please let me know if this problem is specific to me or is this some fault in code.
I can send a changed code if you want.

**Comment by PiTronica** [comment]
Nano into the .DAT file and remove the lables manualy
