### ISSUE TITLE
Path to stressberry-run

### ISSUE THREAD

**Issue by DennisFaucher** [nschloe/stressberry#86]
The install and run instructions are 

[sudo] apt install stress
pip install stressberry (Use pip3 install to be safe)
stressberry-run out.dat
-bash: stressberry-run: command not found

but stressberry-run is not in the current PATH. It looks like stressberry-run is in ~/.local/bin

$ sudo find / -name stressberry-run -print
/home/pi/.local/bin/stressberry-run

**Comment by nschloe** [comment]
Indeed, that's the default bin directory for local installations. You should definitely put that in your PATH.

**Comment by DennisFaucher** [comment]
Thank you
