### ISSUE TITLE
Increase Max Speed 

### ISSUE THREAD

**Issue by bobster316** [nschloe/stressberry#97]
Hi, Is it possible to modify stressberry to increase maximum speed from 1500Mhz to 2147Mhz 
I have overclocked my raspberry pi 4 and have good cooling, i would be interested to see what temps
i get when running at 2147Mhz.

**Comment by nschloe** [comment]
stressberry never sets the cpu frequency, it just measures it. I don't know where to set it either, perhaps somewhere in the firmware config? Anyway, not directly stressberry-related.
